const origins = [
  '42 서울에 지원하며',
  'Color Picker 프로젝트',
  'Full Text Search를 활용한 검색 기능 개발기',
  'GitHub Actions로 AWS S3 배포 자동화 하기',
  'GitHub Actions로 CI/CD 자동화하기',
  'GitHub 프로필 꾸미기',
  'ICT 학점연계 프로젝트 인턴십에 지원하며',
  'NestJS에서 FTP 사용하기',
  'OAuth 2.0이란?',
  'ORM과 Native Query',
  'PM2로 서비스 운영하기',
  'Snake 게임',
  'Tailwind CSS 사용기',
  'Victim cache에 관하여',
  'WYSIWYG 에디터 draft.js의 기록',
  'printf와 scanf에도 반환 값이 있을까?',
  '거품 정렬',
  '선택 정렬',
  '선택 정렬과 삽입 정렬 비교',
  '시간 복잡도 가시적으로 확인해보기',
  '데몬 프로세스에 대한 이해',
  '검색어 강조 알고리즘 개발기',
  '칵테일 셰이커 정렬',
  '코드로 골프하기',
  '마크다운 에디터 제작기',
  '깃허브에 커밋한 파일들 삭제하기',
  '구조체와 클래스의 차이',
  '메모이제이션이란?',
];

const targets = [
  'applying-to-42-seoul',
  'color-picker-project',
  'building-search-with-full-text-search',
  'automate-aws-s3-deployment-with-github-actions',
  'automate-ci-cd-with-github-actions',
  'customize-github-profile',
  'applying-to-ict-internship',
  'using-ftp-in-nestjs',
  'what-is-oauth-2',
  'orm-vs-native-query',
  'running-services-with-pm2',
  'snake-game',
  'using-tailwind-css',
  'about-victim-cache',
  'draftjs-wysiwyg-editor',
  'printf-and-scanf-return-values',
  'bubble-sort',
  'selection-sort',
  'selection-sort-vs-insertion-sort',
  'visualizing-time-complexity',
  'understanding-daemon-processes',
  'search-term-highlighting-algorithm',
  'cocktail-shaker-sort',
  'code-golfing',
  'building-markdown-editor',
  'delete-committed-files-on-github',
  'struct-vs-class',
  'what-is-memoization',
];

const slugify = (slug) => slug.replace(/[^가-힣\w\s-.~]/g, '').replace(/ /g, '-');

export const redirects = async () => {
  return origins.map((origin, index) => ({
    source: '/' + encodeURI(slugify(origin)),
    destination: '/' + targets[index],
    permanent: true,
  }));
};
